@api = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Il9pZCI6IjYxZDhkNDVlYmVhZjkxZmUwNmY3NDIyNyIsIm5vbWJyZSI6IlBhYmxvIiwiZW1haWwiOiJwYWJsb0BtYWlsLmNvbSJ9LCJpYXQiOjE2NDE4NTg0MDUsImV4cCI6MTY0MTk0NDgwNX0.Afa3tRdvGJjFL_-h-Z0s_vjWLnYPlsNvYJfWHZnMu3U
// https://api-rest-nodejs-express.herokuapp.com/ 

### --------------------USUARIOS
### GET
GET {{api}}/api/usuarios
Autorization: {{token}}

### POST usuario
POST {{api}}/api/usuarios
Content-Type: application/json

{
    "nombre": "Pablo",
    "email": "pablo@mail.com",
    "password": "Pablo0705"
}

### PUT usuario
@id = 61d8d45ebeaf91fe06f74227
PUT {{api}}/api/usuarios/{{id}}
Content-Type: application/json
Autorization: {{token}}

{
    "nombre": "Pedro",
    "email": "pepedro@mail.com",
    "password": "DHKVUm4t2"
}

### DELETE usuario
DELETE {{api}}/api/usuarios/{{id}}
Autorization: {{token}}


### ------------------------CURSOS
### GET curso
GET {{api}}/api/cursos
Autorization: {{token}}

### POST curso
POST {{api}}/api/cursos
Autorization: {{token}}
Content-Type: application/json

{
    "titulo": "Git desde 0",
    "descripcion": "curso para aprender git",
    "imagen": "./curso-git.png"
}

### PUT curso
@idCurso = 61d8d4f0beaf91fe06f74233
PUT {{api}}/api/cursos/{{idCurso}}
Autorization: {{token}}
Content-Type: application/json

{
    "titulo": "Nodejs desde 0",
    "descripcion": "curso de nodejs desde 0",
    "imagen": "./curso-nodejs.png"
}

### DELETE curso
DELETE {{api}}/api/cursos/{{idCurso}}
Autorization: {{token}}


### --------------------AUTH de usuarios
### Autenticacion email pass
POST {{api}}/api/auth
Content-Type: application/json

{
    "email": "pablo@mail.com",
    "password": "Pablo0705"
}