@api = http://localhost:3000
// https://api-rest-nodejs-express.herokuapp.com/ 

### --------------------USUARIOS
### GET
GET {{api}}/api/usuarios

### POST usuario
POST {{api}}/api/usuarios
Content-Type: application/json

{
    "nombre": "Carol",
    "email": "carolk@mail.com",
    "password": "DHKVUm4t2"
}

### PUT usuario
@id = 61d4b929b9e89de5d89dbf4e
PUT {{api}}/api/usuarios/{{id}}
Content-Type: application/json

{
    "nombre": "Pedro",
    "email": "pepedro@mail.com",
    "password": "DHKVUm4t2"
}

### DELETE usuario
DELETE {{api}}/api/usuarios/{{id}}


### ------------------------CURSOS
### GET
GET {{api}}/api/cursos