@api = http://localhost:3000
// https://api-rest-nodejs-express.herokuapp.com/ 

### --------------------USUARIOS
### GET
GET {{api}}/api/usuarios

### POST usuario
POST {{api}}/api/usuarios
Content-Type: application/json

{
    "nombre": "Yostin",
    "email": "tocino@mail.com",
    "password": "12457885"
}

### PUT usuario
@id = 61d3b09334e305442c5f6c62
PUT {{api}}/api/usuarios/{{id}}
Content-Type: application/json

{
    "nombre": "David",
    "email": "david@mail.com",
    "password": "123456"
}

### DELETE usuario
DELETE {{api}}/api/usuarios/2

### POST urlencoded
POST {{api}}/api/usuarios
Content-Type: application/x-www-form-urlencoded

{
    "nombre": "David"
}


### ------------------------CURSOS
### GET
GET {{api}}/api/cursos